# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=20)),
                ('etage', models.IntegerField(max_length=20)),
                ('date_affect', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriétaire', models.CharField(max_length=200)),
                ('couleur', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
                ('immat', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationnement.Voiture'),
        ),
    ]
