# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationnement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='etage',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='numero',
        ),
    ]
