# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationnement', '0003_auto_20170515_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='propriétaire',
            new_name='proprietaire',
        ),
    ]
